import { Producto } from "./producto.model";

const productosMock: Producto[] = [
  new Producto("Aceite Girasol Cada Día x 1500 cc", 121.00),
  new Producto("Aceite Girasol Cada Día x 900 cc", 75.00),
  new Producto("Aceite Girasol Florencia x 1500 cc", 121.00),
  new Producto("Aceite Girasol Florencia x 900 cc", 75.00),
  new Producto("Aceite Girasol Ideal x 1500 cc", 121.00),
  new Producto("Aceite Girasol Ideal x 900 cc", 75.00),
  new Producto("Aceite Girasol Primor x 1500 cc", 121.00),
  new Producto("Aceite Girasol Primor x 900 cc", 75.00),
  new Producto("Aceto balsámico Monterrey x 250 cc", 77.00),
  new Producto("Acondicionador Balance doypack Polyana x 300 ml", 50.00),
  new Producto("Acondicionador Coco y leche Algabo x 930 ml", 81.00),
  new Producto("Acondicionador Hidratación Plusbelle x 1 lt", 99.00),
  new Producto("Acondicionador Nutrición Sedal x 340 ml", 120.00),
  new Producto("Agua de Mesa sin gas Nihuil x 2 lt", 34.00),
  new Producto("Agua Mineral Natural con gas Sierra de los Padres x 1,5 lt", 41.00),
  new Producto("Agua Mineral Natural sin gas Sierra de los Padres x 1,5 lt", 41.00),
  new Producto("Agua Mineralizada Con gas Cellier Favaloro x 2 lt", 34.00),
  new Producto("Agua Mineralizada Sin gas Cellier Favaloro x 2 lt", 34.00),
  new Producto("Algodón Hidrófilo clásico Doncella x 140 gr", 77.00),
  new Producto("Anillo de coco Tía Maruca x 250 gr", 54.00),
  new Producto("Arroz Largo fino 00000 Primor x 1 kg", 53.50),
  new Producto("Arroz Largo fino Apóstoles x 1 kg", 54.50),
  new Producto("Arroz No se pasa Apóstoles x 1 kg", 64.00),
  new Producto("Arroz Parboil bolsa Gallo x 500 gr", 43.50),
  new Producto("Arroz Parboil Primor x 1 kg", 66.50),
  new Producto("Atún desmenuzado al natural Supermercado x 170 gr", 69.00),
  new Producto("Atún desmenuzado en aceite Supermercado x 170 gr", 69.00),
  new Producto("Bizcocho arroz azucarado Tía Maruca x 100 gr", 49.00),
  new Producto("Cacao en polvo Arcoa x 180 gr", 39.00),
  new Producto("Cacao en polvo Dulce Ravana x 180 gr", 34.00),
  new Producto("Café Molido La Morenita x 1 kg", 432.00),
  new Producto("Café Molido torrado suave Bonafide x 500 gr", 252.00),
  new Producto("Caldo Gallina Knorr x 12 un", 75.00),
  new Producto("Cebolla comercial Supermercado x 1 kg", 26.00),
  new Producto("Cepillo dental adulto 2-life IBC x 1 un", 38.00),
  new Producto("Cepillo dental infantil 2-life IBC x 1 un", 39.00),
  new Producto("Cerveza botella retornable Quilmes Bajo Cero x 1 lt", 85.00),
  new Producto("Cerveza porrón retornable Quilmes Clásica x 340 cc", 35.00),
  new Producto("Cerveza rubia botella retornable Isenbeck x 1 lt", 90.00),
  new Producto("Cerveza rubia en lata Isenbeck x 473 cc", 60.00),
  new Producto("Crema de leche Para cocinar tenor graso 20% Armonía x 200 cc", 71.00),
  new Producto("Crema de leche Sancor x 200 gr", 79.00),
  new Producto("Desodorante Deo en aerosol AP antibacterial Rexona x 150 ml", 99.00),
  new Producto("Desodorante Deo Protect & Care Fem Nivea x 150 ml", 99.00),
  new Producto("Desodorante En aerosol body spray gold Axe x 150 ml", 99.00),
  new Producto("Desodorante Men Deo Sensitive Nivea x 150 ml", 99.00),
  new Producto("Desodorante Roll on Plusbelle Care x 50 ml", 76.00),
  new Producto("Desodorante W Deo en aerosol AP antibacterial Rexona x 150 ml", 99.00),
  new Producto("Dulce de batata Estuche Esnaola x 500 gr", 83.00),
  new Producto("Dulce de Leche Clásico Armonía x 400 gr", 91.00),
  new Producto("Dulce de Leche Tradicional Artesanal San Ignacio x 400 gr", 91.00),
  new Producto("Dulce de membrillo Estuche Esnaola x 500 gr", 88.00),
  new Producto("Espinazo novillo Supermercado x 1 kg", 65.00),
  new Producto("Esponja Con fibra \"no ray\" Cuidado Azul Virulana x 1 un", 41.50),
  new Producto("Esponja Con fibra Multiuso Virulana x 1 un", 25.90),
  new Producto("Fajitas clásicas Tía Maruca x 150 gr", 55.00),
  new Producto("Fiambre de cerdo comercial Supermercado x 1 kg", 219.00),
  new Producto("Fideos Codito Canale x 500 gr", 33.00),
  new Producto("Fideos Spaghetti Canale x 500 gr", 33.00),
  new Producto("Fideos Spaghetti Libre de Gluten Matarazzo x 500 gr", 108.00),
  new Producto("Fideos Tallarín Canale x 500 gr", 33.00),
  new Producto("Fideos Tirabuzón Canale x 500 gr", 33.00),
  new Producto("Fideos Tirabuzón Libre de Gluten Matarazzo x 500 gr", 108.00),
  new Producto("Flan Vainilla Ravana x 60 gr", 23.00),
  new Producto("Flan Vainilla Royal x 60 gr", 29.00),
  new Producto("Galleta Marinera clásica Tía Maruca x 350 gr", 86.00),
  new Producto("Galletitas de agua Pack x 3 Criollitas x 300 gr", 73.00),
  new Producto("Galletitas dulces Clásicas Lincoln x 153 gr", 52.00),
  new Producto("Galletitas dulces Clásicas Vocación x 170 gr", 27.50),
  new Producto("Galletitas dulces Rellenas Duquesa x 115 gr", 49.00),
  new Producto("Galletitas dulces Rellenas Rumba x 112 gr", 41.00),
  new Producto("Galletitas dulces surtidas Dale x 400 gr", 62.00),
  new Producto("Garbanzos Remojados Inalpa x 350 gr", 35.00),
  new Producto("Gaseosa Cola Cunnington x 1,5 lt", 53.00),
  new Producto("Gaseosa Cola Cunnington x 2,25 lt", 64.00),
  new Producto("Gaseosa Cola original Coca Cola x 1,25 lt", 82.00),
  new Producto("Gaseosa Cola original Coca Cola x 1,5 lt", 82.00),
  new Producto("Gaseosa Cola sin azúcar Cunnington x 1,5 lt", 53.00),
  new Producto("Gaseosa Cola sin azúcar Cunnington x 2,25 lt", 58.00),
  new Producto("Gaseosa Lima limón light Cunnington x 2,25 lt", 58.00),
  new Producto("Gaseosa Naranja light Cunnington x 2,25 lt", 58.00),
  new Producto("Gelatina Gelatina cereza Ravana x 50 gr", 34.00),
  new Producto("Harina de maíz LG Prestopronta x 750 gr", 81.00),
  new Producto("Harina de maíz Morixe x 500 gr", 32.00),
  new Producto("Harina de trigo 000 Morixe x 1 kg", 33.00),
  new Producto("Harina de trigo 0000 Morixe x 1 kg", 46.00),
  new Producto("Harina de trigo Leudante Morixe x 1 kg", 52.00),
  new Producto("Huevos blancos Supermercado x 6 un", 59.00),
  new Producto("Insecticida Mata cucarachas Cuca Trap x 380 ml", 120.00),
  new Producto("Insecticida Mata moscas y mosquitos Mosqui Trap x 370 ml", 115.00),
  new Producto("Jabón de tocador Antibacterial aloe Rexona x 90 gr", 39.00),
  new Producto("Jabón de tocador Antibacterial aloe x 3 un Rexona x 90 gr", 99.00),
  new Producto("Jabón de tocador Fresia y Muguet Duc x 110 gr", 23.50),
  new Producto("Jabón de tocador Lima y madreselva Duc x 110 gr", 23.50),
  new Producto("Jabón de tocador Multicolor x 3 unid Kenia x 80 gr", 49.50),
  new Producto("Jabón de tocador Sándalos y Casis Duc x 110 gr", 23.50),
  new Producto("Jabón de tocador Ylang y Ambar Duc x 110 gr", 23.50),
  new Producto("Jabón en pan para ropa Gigante x 120 gr", 16.00),
  new Producto("Jabón en polvo Clásico Zorro x 800 gr", 106.00),
  new Producto("Jabón en polvo Primer lavado Ala x 3 kg", 369.00),
  new Producto("Jabón líquido de manos Doypack green tea Algabo x 300 ml", 63.00),
  new Producto("Jabón líquido para ropa Baja espuma doypack Ala x 1400 ml", 205.00),
  new Producto("Jabón líquido para ropa Baja espuma doypack Ecovita x 1500 ml", 158.00),
  new Producto("Jabón líquido para ropa Doypack Ace x 1400 ml", 204.00),
  new Producto("Jabón líquido para ropa Doypack Netic x 3 lt", 295.00),
  new Producto("Jabón líquido para ropa Doypack Netic x 800 ml", 90.00),
  new Producto("Jugo de limón Menoyo x 250 cc", 72.00),
  new Producto("Jugo en polvo Naranja Dulce Arcor x 20 gr", 11.00),
  new Producto("Jugo en Polvo Naranja Verao x 10 gr", 6.00),
  new Producto("Jugo listo Manzana Del Valle x 1 lt", 49.50),
  new Producto("Jugo listo Multifruta Del Valle x 1 lt", 49.50),
  new Producto("Jugo listo Naranja Del Valle x 1 lt", 49.50),
  new Producto("Lavandina Común Odex x 2 lt", 86.00),
  new Producto("Lavandina Tradicional concentrada Ayudín x 1 lt", 37.50),
  new Producto("Lavavajilla Limón Ala Ultra x 500 ml", 70.00),
  new Producto("Lavavajilla Limón Gigante x 545 cc", 80.00),
  new Producto("Lavavajilla Limón Zorro Ultra x 300 ml", 58.00),
  new Producto("Leche chocolatada Tregar x 1 lt", 82.00),
  new Producto("Leche en polvo Entera Ilolay x 400 gr", 178.00),
  new Producto("Leche en polvo Entera Inst. Fortificada con Vit. A y D Pouch Purísima x 400 gr", 173.00),
  new Producto("Leche Fresca Entera tenor graso 3% Armonía x 1 lt", 40.25),
  new Producto("Leche Fresca Parcialmente Descremada tenor graso 1% Armonía x 1 lt", 40.25),
  new Producto("Leche Fresca Parcialmente Descremada tenor graso 2% Armonía x 1 lt", 40.25),
  new Producto("Leche larga vida Entera UHT Apóstoles x 1 lt", 45.00),
  new Producto("Leche larga vida Parcialmente descremada UHT Apóstoles x 1 lt", 45.00),
  new Producto("Lechuga Supermercado x 1 kg", 59.00),
  new Producto("Limpiador Baño doypack Ecovita x 500 ml", 53.00),
  new Producto("Limpiador Baño doypack Odex x 450 ml", 54.00),
  new Producto("Limpiador Cocina Antigrasa doypack Odex x 450 ml", 54.00),
  new Producto("Limpiador Cocina Cocina doypack Ecovita x 500 ml", 53.00),
  new Producto("Limpiador Cremoso Flores naranja con microscopio Cif x 500 ml", 90.00),
  new Producto("Limpiador de piso Colores Citrus NH3 x 1800 cc", 90.00),
  new Producto("Limpiador de piso Con Amoníaco botella NH3 x 900 cc", 90.00),
  new Producto("Limpiador de piso Lavanda en botella Ecovita x 900 ml", 60.00),
  new Producto("Limpiador de piso Lavanda Mr Músculo x 1800 cc", 115.00),
  new Producto("Limpiador Vidrios doypack Ecovita x 500 ml", 53.00),
  new Producto("Limpiador Vidrios doypack Odex x 450 ml", 54.00),
  new Producto("Limpiador Vidrios y multiuso doypcak Procenex x 820 ml", 99.00),
  new Producto("Limpiador Vidrios y multiuso repuesto doypack Mr Músculo x 450 ml", 46.50),
  new Producto("Manteca Primer Premio x 200 gr", 94.00),
  new Producto("Manteca Sancor x 100 gr", 69.00),
  new Producto("Manzana comercial Supermercado x 1 kg", 50.00),
  new Producto("Mate Cocido Saquitos Chamigo x 25 un", 36.00),
  new Producto("Mate cocido Saquitos Playadito x 50 un", 100.00),
  new Producto("Mate cocido Suave Unión x 25 un", 50.00),
  new Producto("Mayonesa Sin tacc doypack Fanacoa x 475 gr", 62.00),
  new Producto("Medallones de carne 276 gr Swift x 4 un", 115.00),
  new Producto("Medallón de carne Express 276 gr Paty x 4 un", 150.00),
  new Producto("Mermelada Ciruela Arcor x 454 gr", 95.00),
  new Producto("Mermelada Durazno Arcor x 454 gr", 95.00),
  new Producto("Mermelada Familiar Durazno en frasco Dulcor x 454 gr", 75.00),
  new Producto("Oblea Rellena con pasta de Turrón y Maní Billiken x 25 gr", 9.00),
  new Producto("Oleo calcáreo Botella Sanicare x 1000 ml", 166.00),
  new Producto("Oleo calcáreo Botella Sanicare x 220 ml", 76.00),
  new Producto("Oleo calcáreo Doypack Sanicare x 500 ml", 108.00),
  new Producto("Orégano Sobre La Parmesana x 25 gr", 32.00),
  new Producto("Pan lactal De Mesa Chico Lactal x 335 gr", 67.00),
  new Producto("Pan lactal De Mesa Grande Lactal x 560 gr", 124.00),
  new Producto("Pan lactal De Salvado Chico Lactal x 350 gr", 73.00),
  new Producto("Pan lactal De Salvado Grande Lactal x 630 gr", 136.00),
  new Producto("Pan lactal Familiar Veneziana x 600 gr", 105.00),
  new Producto("Pan para hamburguesa Lactal x 210 gr", 52.00),
  new Producto("Pan para hamburguesa Veneziana x 210 gr", 45.00),
  new Producto("Pan para pancho Lactal x 210 gr", 52.00),
  new Producto("Pan para pancho Veneziana x 210 gr", 45.00),
  new Producto("Pan rallado Mama Cocina x 1 kg", 104.00),
  new Producto("Pan rallado Morixe x 1 kg", 89.00),
  new Producto("Pan rallado Morixe x 500 gr", 54.00),
  new Producto("Papa comercial Supermercado x 1 kg", 26.00),
  new Producto("Papel higiénico Doble hoja 20 mts Elite x 4 un", 90.00),
  new Producto("Papel higiénico Doble hoja blanco 30 mts Sweety x 4 un", 112.00),
  new Producto("Papel higiénico Doble hoja blanco 50 mts Campanita XL x 4 un", 214.00),
  new Producto("Papel higiénico Hoja Simple Flor Cadenas 80 mts Elite x 4 un", 130.00),
  new Producto("Pasta dental 2 Fluor Fresh Dent x 140 gr", 103.00),
  new Producto("Pasta dental Dientes blanco Odol x 90 gr", 79.00),
  new Producto("Pasta dental Kid´s con fluor, sabor Tutti Frutti Fresh Dent x 90 gr", 70.00),
  new Producto("Pasta dental Ultra blanqueadora Colgate x 90 gr", 141.00),
  new Producto("Pañales descartables Supersec Talle G Pampers x 46 un", 650.00),
  new Producto("Pañales descartables Supersec Talle M Pampers x 54 un", 650.00),
  new Producto("Pañales descartables Supersec Talle P Pampers x 30 un", 360.00),
  new Producto("Pañales descartables Supersec Talle XG Pampers x 36 un", 650.00),
  new Producto("Pañales descartables Supersec Talle XXG Pampers x 34 un", 650.00),
  new Producto("Pañales descartables Triple Protección G Huggies x 22 un", 330.00),
  new Producto("Pañales descartables Triple Protección M Huggies x 26 un", 330.00),
  new Producto("Pañales descartables Triple Protección XG Huggies x 18 un", 330.00),
  new Producto("Pañales descartables Triple Protección XXG Huggies x 17 un", 330.00),
  new Producto("Pañales descartables Ultrasec Talle G Babysec x 22 un", 305.00),
  new Producto("Pañales descartables Ultrasec Talle M Babysec x 26 un", 305.00),
  new Producto("Pañales descartables Ultrasec Talle XG Babysec x 18 un", 305.00),
  new Producto("Pañales descartables Ultrasec Talle XXG Babysec x 16 un", 305.00),
  new Producto("Paño Amarillo Multiuso Twist Virulana x 1 un", 43.90),
  new Producto("Pañuelos descartables Doble hoja Campanita Box x 75 un", 40.00),
  new Producto("Pañuelos descartables Minipocket Elite x 6 un", 45.00),
  new Producto("Pepas con membrillo Tía Maruca x 250 gr", 54.00),
  new Producto("Picada común Supermercado x 1 kg", 169.00),
  new Producto("Pollo Entero aditivado con menudos fresco o congelado Supermercado x 1 kg", 108.00),
  new Producto("Postre Arroz con leche clásico Sublime x 160 gr", 40.00),
  new Producto("Postre Chocolate Blanco con Dulce de Leche x 2 unidades Sublime x 100 gr", 48.50),
  new Producto("Postre Chocolate con Dulce de Leche Shimy x 120 gr", 36.00),
  new Producto("Postre Chocolate con Dulce de Leche x 2 unidades Sublime x 100 gr", 48.50),
  new Producto("Postre Chocolate Shimy x 120 gr", 36.00),
  new Producto("Postre Dulce de Leche con Dulce de Leche x 2 unidades Sublime x 100 gr", 48.50),
  new Producto("Postre Dulce de Leche Shimy x 120 gr", 36.00),
  new Producto("Postre Flan vainilla con caramelo x 2 unidades Sublime x 100 gr", 60.00),
  new Producto("Postre Vainilla con Dulce de Leche Shimy x 120 gr", 36.00),
  new Producto("Postre Vainilla con Dulce de Leche x 2 unidades Sublime x 100 gr", 48.50),
  new Producto("Postre Vainilla Ravana x 120 gr", 23.00),
  new Producto("Postre Vainilla Shimy x 120 gr", 36.00),
  new Producto("Premezclas Chipa Lucchetti x 250 gr", 135.00),
  new Producto("Preservativos Ultra finos Tulipán x 6 un", 160.00),
  new Producto("Protector diario Clásicos con gel absorvente Ladysoft x 20 un", 65.00),
  new Producto("Protector diario Pocket anatómico c/deo Doncella x 20 un", 50.00),
  new Producto("Protector diario Pocket anatómico s/deo Doncella x 20 un", 50.00),
  new Producto("Protector solar Sun Protect & Hydrate 15 FPS Nivea x 200 ml", 415.00),
  new Producto("Protector solar Sun Protect & Hydrate 30 FPS Nivea x 200 ml", 470.00),
  new Producto("Puré de papas Morixe x 125 gr", 58.00),
  new Producto("Puré de papas Morixe x 200 gr", 93.00),
  new Producto("Queso cremoso Horma La Paulina x 1 kg", 329.00),
  new Producto("Queso de máquina comercial Supermercado x 1 kg", 359.00),
  new Producto("Queso port salut Light horma La Paulina x 1 kg", 370.00),
  new Producto("Queso rallado Ilolay x 120 gr", 125.00),
  new Producto("Queso rallado La Paulina x 150 gr", 161.00),
  new Producto("Queso rallado Reggianito Sancor x 190 gr", 200.00),
  new Producto("Queso untable Crematto light Milkaut x 290 gr", 110.00),
  new Producto("Queso untable Crematto Milkaut x 290 gr", 110.00),
  new Producto("Queso untable Entero San Ignacio x 480 gr", 138.00),
  new Producto("Queso untable García x 290 gr", 110.00),
  new Producto("Rebozador Morixe x 1 kg", 89.00),
  new Producto("Rebozador Morixe x 500 gr", 54.00),
  new Producto("Repelente Aerosol Fuyí x 165 ml", 76.50),
  new Producto("Repelente Crema en pomo Vais x 200 gr", 85.00),
  new Producto("Repelente Kids Vais x 200 ml", 106.00),
  new Producto("Repelente Líquido en spray Vais x 200 ml", 91.00),
  new Producto("Roast beef novillo Supermercado x 1 kg", 229.00),
  new Producto("Rollo de cocina 60 paños Elite x 3 un", 99.00),
  new Producto("Rollo de cocina 60 paños Sweety x 3 un", 91.00),
  new Producto("Sal fina Dos Anclas x 500 gr", 35.00),
  new Producto("Sal fina Estuche Celusal x 500 gr", 43.00),
  new Producto("Salchichas Fun 190 gr Patyviena x 6 un", 75.00),
  new Producto("Salchichas Junior 190 gr Swift x 6 un", 65.00),
  new Producto("Servilletas Blanca Elite x 70 un", 52.00),
  new Producto("Shampoo Balance doypack Polyana x 300 ml", 50.00),
  new Producto("Shampoo Hidratación Plusbelle x 1 lt", 99.00),
  new Producto("Shampoo infantil 3 en 1 PH balanceado Suave kids x 200 ml", 105.00),
  new Producto("Shampoo infantil Cabellos perfumados Johnson & Johnson x 200 ml", 145.00),
  new Producto("Shampoo infantil Sandía dulce Algabo Kids x 350 ml", 95.00),
  new Producto("Shampoo Nutrición Sedal x 340 ml", 120.00),
  new Producto("Shampoo para bebé Extra suave Algabo Baby x 444 ml", 110.00),
  new Producto("Suavizante Felices sueños doypack Vivere x 450 ml", 132.00),
  new Producto("Suavizante Jardín de geranios Zorro x 900 ml", 80.00),
  new Producto("Tabletas para mosquitos Repuesto Raid x 24 un", 132.00),
  new Producto("Tampones Tamaño medio Intima x 16 un", 99.00),
  new Producto("Tampones Tamaño medio Intima x 8 un", 56.00),
  new Producto("Tampones Tamaño super Intima x 16 un", 99.00),
  new Producto("Tampones Tamaño super Intima x 8 un", 56.00),
  new Producto("Tapa de Asado novillo Supermercado x 1 kg", 229.00),
  new Producto("Tapa de tarta Criolla Don Celedonio x 360 gr", 54.00),
  new Producto("Tapa de tarta Pascualina mediana Mendía x 230 gr", 41.00),
  new Producto("Tapas de empanadas Hojaldre Don Celedonio x 15 un", 55.00),
  new Producto("Tapas de empanadas Mendía x 12 un", 46.50),
  new Producto("Tapas de pastel Mendía x 24 un", 67.50),
  new Producto("Toalla Femenina Confort Normales Tela Suave con Alas x 8 unidades Ladysoft x 8 un", 49.00),
  new Producto("Toalla Femenina Especial Suave con Alas Siempre Libre x 8 un", 67.00),
  new Producto("Toalla Femenina Pocket normal con alas duopack tela suave sin deo Doncella x 16 un", 58.00),
  new Producto("Toalla Femenina Pocket ultrafinas tela suave Doncella x 8 un", 41.00),
  new Producto("Toalla femenina Protección plus suave Always x 16 un", 100.00),
  new Producto("Toallas húmedas Doypack Sanicare x 100 un", 74.00),
  new Producto("Toallas húmedas FP Sanicare x 100 un", 144.00),
  new Producto("Tostada de arroz con sal Tía Maruca x 120 gr", 56.00),
  new Producto("Tostada de arroz grande Tía Maruca x 160 gr", 96.00),
  new Producto("Tostada de arroz sin sal Tía Maruca x 120 gr", 56.00),
  new Producto("Té común Saquitos La Morenita x 25 un", 32.00),
  new Producto("Té común Saquitos Taraguí x 25 un", 39.00),
  new Producto("Vinagre De alcohol Alcazar x 500 cc", 25.00),
  new Producto("Vinagre De manzana Alcazar x 1000 cc", 72.00),
  new Producto("Vino Blanco Tetrabrick Arizu x 1 lt", 55.00),
  new Producto("Vino Blanco Tetrabrick Crespi x 1 lt", 55.00),
  new Producto("Vino Tinto Clásico Resero x 1125 ml", 75.00),
  new Producto("Vino Tinto Tetrabrick Arizu x 1 lt", 55.00),
  new Producto("Vino Tinto Tetrabrick Crespi x 1 lt", 55.00),
  new Producto("Vino Tinto Tradicional Michel Torino x 1125 ml", 94.00),
  new Producto("Yerba mate Compuesta elaborada con palo Chamigo x 500 gr", 89.00),
  new Producto("Yerba mate Con palo suave Unión x 1 kg", 225.00),
  new Producto("Yerba mate Junior Rosamonte x 1 kg", 193.00),
  new Producto("Yerba mate Junior Rosamonte x 500 gr", 100.00),
  new Producto("Yerba mate Suave compuesta elaborada con palo Nobleza Gaucha x 500 gr", 100.00),
  new Producto("Yerba mate Tradicional Amanda x 500 gr", 112.50),
  new Producto("Yogur batido Entero Frutilla 2 x 120 gr Ilolay x 240 gr", 39.00),
  new Producto("Yogur batido Entero Vainilla 2 x 120 gr Ilolay x 240 gr", 39.00),
  new Producto("Yogur Bebible descremado Frutilla Sachet Vida x 900 gr", 77.00),
  new Producto("Yogur Bebible descremado Frutos del Bosque Sachet Vida x 900 gr", 77.00),
  new Producto("Yogur Bebible descremado Vainilla Sachet Vida x 900 gr", 77.00),
  new Producto("Yogur bebible Tetratop Descremado Frutilla Ilolay x 1 kg", 74.50),
  new Producto("Yogur bebible Tetratop Descremado Vainilla Ilolay x 1 kg", 74.50),
  new Producto("Yogur bebible Tetratop Entero Durazno Ilolay x 1 kg", 74.50),
  new Producto("Yogur bebible Tetratop Entero Frutilla Ilolay x 1 kg", 74.50),
  new Producto("Yogur bebible Tetratop Entero Vainilla Ilolay x 1 kg", 74.50),
  new Producto("Yogur Cremoso entero Vainilla x 2 unidades Primeros Sabores x 120 gr", 45.00),
  new Producto("Yogur Firme descremado frutilla pote Vida x 190 gr", 36.00),
  new Producto("Yogur firme Entero Frutilla 2 x 120 gr Ilolay x 240 gr", 39.00),
  new Producto("Yogur firme Entero Vainilla 2 x 120 gr Ilolay x 240 gr", 39.00),
  new Producto("Zapallo anco comercial Supermercado x 1 kg", 46.00)
];

export default productosMock;